# Generated by Django 6.0.3 on 2026-03-08 17:38

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_email', '0002_email_is_read'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='email',
            options={'ordering': ['-timestamp']},
        ),
        migrations.RemoveField(
            model_name='email',
            name='is_read',
        ),
        migrations.RemoveField(
            model_name='email',
            name='sent_at',
        ),
        migrations.AddField(
            model_name='email',
            name='read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='email',
            name='slug',
            field=models.SlugField(default=uuid.uuid4, unique=True),
        ),
        migrations.AddField(
            model_name='email',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='email',
            name='folder',
            field=models.CharField(choices=[('inbox', 'Inbox'), ('sent', 'Sent'), ('drafts', 'Drafts'), ('trash', 'Trash')], max_length=10),
        ),
        migrations.AlterField(
            model_name='email',
            name='subject',
            field=models.CharField(max_length=200),
        ),
    ]
