# Generated by Django 6.0.3 on 2026-03-14 11:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_email', '0003_alter_email_options_remove_email_is_read_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='email',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Письмо', 'verbose_name_plural': 'Письма'},
        ),
        migrations.AlterField(
            model_name='email',
            name='body',
            field=models.TextField(verbose_name='Текст письма'),
        ),
        migrations.AlterField(
            model_name='email',
            name='folder',
            field=models.CharField(choices=[('inbox', 'Входящие'), ('sent', 'Отправленные'), ('drafts', 'Черновики'), ('trash', 'Корзина')], default='inbox', max_length=10, verbose_name='Папка'),
        ),
        migrations.AlterField(
            model_name='email',
            name='read',
            field=models.BooleanField(default=False, verbose_name='Прочитано'),
        ),
        migrations.AlterField(
            model_name='email',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_emails', to=settings.AUTH_USER_MODEL, verbose_name='Получатель'),
        ),
        migrations.AlterField(
            model_name='email',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_emails', to=settings.AUTH_USER_MODEL, verbose_name='Отправитель'),
        ),
        migrations.AlterField(
            model_name='email',
            name='slug',
            field=models.SlugField(default=uuid.uuid4, unique=True, verbose_name='Уникальный идентификатор'),
        ),
        migrations.AlterField(
            model_name='email',
            name='subject',
            field=models.CharField(max_length=200, verbose_name='Тема'),
        ),
        migrations.AlterField(
            model_name='email',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата отправки'),
        ),
        migrations.AddIndex(
            model_name='email',
            index=models.Index(fields=['recipient', 'folder'], name='app_email_e_recipie_44108e_idx'),
        ),
        migrations.AddIndex(
            model_name='email',
            index=models.Index(fields=['sender', 'folder'], name='app_email_e_sender__9055d4_idx'),
        ),
        migrations.AddIndex(
            model_name='email',
            index=models.Index(fields=['read'], name='app_email_e_read_576f22_idx'),
        ),
        migrations.AddIndex(
            model_name='email',
            index=models.Index(fields=['timestamp'], name='app_email_e_timesta_e5e82f_idx'),
        ),
    ]
